spring:
  datasource:
    url: jdbc:mysql://mysqldbdev.ctwc6abmvhxh.eu-north-1.rds.amazonaws.com:3306/mysqldbdev
    username: user
    password: mysqldbdev
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
